int random_joueur();
int random_int(int min, int max);
void joueur_humain(char *joueur, int tour, int adversaire, char *selection, int othellier[][8]);
void joueur_ordinateur(char *joueur, int tour, int adversaire, char *selection, int othellier[][8]);
void selection_aleatoire(int *x, int *y, int othellier[][8]);
void joueur_suivant(int *tour, int *adversaire, int othellier[][8], int *cases_disponibles);
void initialiser_othellier(int othellier[][8]);
void dessiner_othellier(int othellier[][8]);
void afficher_score (char joueur[][20], int othellier[][8]);
void afficher_score_final(int mode, char joueur[][20], int othellier[][8]);
void afficher_case_selectionne (char *selection);
void calculer_nombre_cases(int *nombre_cases, int othellier[][8]);
void convertir_en_coordonnees(char *selection, int *x, int *y);
void convertir_en_selection(char *selection, int x, int y);
void delay_ms(int temps_ms);
int pas_valide(int pas_x, int pas_y);
int symbole(int valeur);
void joueur_ordinateur_intelligent(char *joueur, int tour, int adversaire, char *selection, int othellier[][8]);
void selection_intelligente(int *x, int *y, int tour, int adversaire, int othellier[][8]);
